export const Get_AdminList_BySearchAndPage = '/getAdminListBySearchAndPage'
export const GetAdminListBySearchCount = '/getAdminListBySearchCount'
export const DelAdminById = '/delAdminById'
export const getAdminInfoById = '/delAdminById'
export const UpdateAdminIndoById = '/updateAdminInfoById'
export const AddAdmin = '/addAdmin'
export const Admin_login = '/admin_login'
